name: Validate

on: [push, pull_request]

permissions: read-all

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # checkout@v6
      - uses: jonobr1/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      # setup-node@v6
      - uses: jonobr1/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version: '24.14.1'
          cache: 'npm'
      - name: Install modules
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Check TypeScript sample
        run: npx tsc --noEmit --skipLibCheck tests/typescript/index.ts
